export const rescueImage = "https://images.unsplash.com/photo-1601758064224-c3c14733a968?auto=format&fit=crop&w=1400&q=80";

export const mockCampaigns = [
  {
    _id: "demo-1",
    title: "Emergency leg surgery for Bruno",
    description: "Bruno was found near a market with a fractured hind leg and needs surgery, medicines, and supervised recovery care.",
    category: "surgery",
    urgency: "urgent",
    isUrgent: true,
    location: "Pune",
    raisedAmount: 78000,
    goalAmount: 125000,
    donationCount: 154,
    deadline: new Date(Date.now() + 1000 * 60 * 60 * 24 * 9).toISOString(),
    coverImage: rescueImage,
    creator: {
      name: "Anaya Rescue Trust",
      email: "organizer@aniRescue.org",
      location: "Pune, Maharashtra",
      organization: "Anaya Animal Rescue",
    },
    medicalDocuments: [
      {
        _id: "doc-1",
        title: "Vet diagnosis report",
        fileType: "application/pdf",
        uploadedAt: new Date().toISOString(),
        url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      },
      {
        _id: "doc-2",
        title: "Surgery estimate",
        fileType: "application/pdf",
        uploadedAt: new Date().toISOString(),
        url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      },
    ],
    updates: [
      { stage: "before", text: "Bruno was rescued and moved to the partner clinic for scans.", timestamp: new Date().toISOString() },
      { stage: "during", text: "Pain support has started. Surgery is scheduled after blood work clearance.", timestamp: new Date().toISOString() },
    ],
    recentDonors: [
      { name: "Riya M.", amount: 3000, createdAt: new Date().toISOString() },
      { name: "Anonymous donor", amount: 1500, anonymous: true, createdAt: new Date().toISOString() },
    ],
  },
  {
    _id: "demo-2",
    title: "Treatment for Maya's deep wound infection",
    description: "Maya needs wound cleaning, antibiotics, nutrition support, and daily dressing for three weeks.",
    category: "treatment",
    urgency: "critical",
    isUrgent: true,
    location: "Delhi",
    raisedAmount: 42000,
    goalAmount: 95000,
    donationCount: 86,
    deadline: new Date(Date.now() + 1000 * 60 * 60 * 24 * 5).toISOString(),
    coverImage: "https://images.unsplash.com/photo-1583511655826-05700442b31b?auto=format&fit=crop&w=1400&q=80",
    creator: { name: "Street Paws Delhi", email: "care@streetpaws.example", location: "Delhi", organization: "Street Paws Delhi" },
    medicalDocuments: [],
  },
  {
    _id: "demo-3",
    title: "Post-surgery recovery care for Chotu",
    description: "Chotu survived a road accident and now needs medicines, nutrition, and foster recovery care.",
    category: "recovery",
    urgency: "normal",
    location: "Bengaluru",
    raisedAmount: 61000,
    goalAmount: 80000,
    donationCount: 101,
    deadline: new Date(Date.now() + 1000 * 60 * 60 * 24 * 15).toISOString(),
    coverImage: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1400&q=80",
    creator: { name: "Care Kennel Bengaluru", email: "hello@carekennel.example", location: "Bengaluru", organization: "Care Kennel" },
    medicalDocuments: [],
  },
];

export const mockStats = {
  totalDonations: 18420,
  totalDonors: 9234,
  totalFundsRaised: 12840000,
  animalsRescued: 842,
  totalUsers: 12800,
  totalCampaigns: 420,
  pendingApprovals: 18,
};
