### Register User
POST http://localhost:5000/api/register
Content-Type: application/json

{
  "name": "Pawan Kumar",
  "email": "pawan7@gmail.com",
  "password": "pawan@45678"
}

### Login User
POST http://localhost:5000/api/login
Content-Type: application/json

{
  "email": "pawan7@gmail.com",
  "password": "pawan@45678"
}

###LOGOUT
POST http://localhost:5000/api/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZmFjMTNiMjFiNmI3MzU4NDJkMzE2OCIsImVtYWlsIjoicGF3YW43QGdtYWlsLmNvbSIsImlhdCI6MTc3ODA0MTMyNywiZXhwIjoxNzc4MTI3NzI3fQ.5v02rgUgCUGabKoqfJWPUuitHliFkyLqtnp_mCfzroY

### Refresh Token
POST http://localhost:5000/api/refresh-token
Content-Type: application/json

{
  "refreshToken": "your_refresh_token_here"
}



### Get Profile
GET http://localhost:5000/api/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZmFjMTNiMjFiNmI3MzU4NDJkMzE2OCIsImVtYWlsIjoicGF3YW43QGdtYWlsLmNvbSIsImlhdCI6MTc3ODA0MTMyNywiZXhwIjoxNzc4MTI3NzI3fQ.5v02rgUgCUGabKoqfJWPUuitHliFkyLqtnp_mCfzroY
### Create Donation Order
POST http://localhost:5000/api/donations/create-order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZmFjMTNiMjFiNmI3MzU4NDJkMzE2OCIsImVtYWlsIjoicGF3YW43QGdtYWlsLmNvbSIsImlhdCI6MTc3ODA0MTMyNywiZXhwIjoxNzc4MTI3NzI3fQ.5v02rgUgCUGabKoqfJWPUuitHliFkyLqtnp_mCfzroY

{
  "campaignId": "<your_campaign_id>",
  "amount": 500
}

### Confirm Donation Payment
POST http://localhost:5000/api/donations/confirm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZmFjMTNiMjFiNmI3MzU4NDJkMzE2OCIsImVtYWlsIjoicGF3YW43QGdtYWlsLmNvbSIsImlhdCI6MTc3ODA0MTMyNywiZXhwIjoxNzc4MTI3NzI3fQ.5v02rgUgCUGabKoqfJWPUuitHliFkyLqtnp_mCfzroY

{
  "donationId": "<your_donation_id>",
  "razorpayPaymentId": "<razorpay_payment_id>",
  "razorpaySignature": "<razorpay_signature>"
}

### Get Donation History
GET http://localhost:5000/api/donations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZmFjMTNiMjFiNmI3MzU4NDJkMzE2OCIsImVtYWlsIjoicGF3YW43QGdtYWlsLmNvbSIsImlhdCI6MTc3ODA0MTMyNywiZXhwIjoxNzc4MTI3NzI3fQ.5v02rgUgCUGabKoqfJWPUuitHliFkyLqtnp_mCfzroY

### Get Donation Details
GET http://localhost:5000/api/donations/<your_donation_id>
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZmFjMTNiMjFiNmI3MzU4NDJkMzE2OCIsImVtYWlsIjoicGF3YW43QGdtYWlsLmNvbSIsImlhdCI6MTc3ODA0MTMyNywiZXhwIjoxNzc4MTI3NzI3fQ.5v02rgUgCUGabKoqfJWPUuitHliFkyLqtnp_mCfzroY



### Send OTP
POST http://localhost:5000/api/auth/send-otp
Content-Type: application/json

{
  "email": "test@gmail.com"
}


### Verify OTP
POST http://localhost:5000/api/auth/verify-otp
Content-Type: application/json

{
  "email": "test@gmail.com",
  "otp": "123456"
}